"""
Assessment helpers for turning raw backtest metrics into user-facing labels.

All numeric thresholds are imported from config.py — none are defined here.
The `notes` field is generated by descriptions.build_assessment_notes(), which
uses parameterized templates filled with computed metric values.
"""
from __future__ import annotations

from typing import Any

from engine.config import (
    DRAWDOWN_TOLERANCE_LOW_MAX_PCT,
    DRAWDOWN_TOLERANCE_LOW_MAX_RECOVERY_DAYS,
    DRAWDOWN_TOLERANCE_MEDIUM_MAX_PCT,
    DRAWDOWN_TOLERANCE_MEDIUM_MAX_RECOVERY_DAYS,
    GRADE_A_MIN_SCORE,
    GRADE_B_MIN_SCORE,
    GRADE_B_PLUS_MIN_SCORE,
    GRADE_C_MIN_SCORE,
    GRADE_C_PLUS_MIN_SCORE,
    GRADE_CONSISTENCY_SCORE_EXCELLENT_MIN_PF,
    GRADE_CONSISTENCY_SCORE_EXCELLENT_MIN_WR,
    GRADE_CONSISTENCY_SCORE_FAIR_MIN_PF,
    GRADE_CONSISTENCY_SCORE_GOOD_MIN_PF,
    GRADE_CONSISTENCY_SCORE_GOOD_MIN_WR,
    GRADE_CONSISTENCY_SCORE_MODERATE_MIN_PF,
    GRADE_CONSISTENCY_SCORE_MODERATE_MIN_WR,
    GRADE_DRAWDOWN_SCORE_EXCELLENT_MAX_PCT,
    GRADE_DRAWDOWN_SCORE_FAIR_MAX_PCT,
    GRADE_DRAWDOWN_SCORE_GOOD_MAX_PCT,
    GRADE_DRAWDOWN_SCORE_MODERATE_MAX_PCT,
    GRADE_DRAWDOWN_SCORE_POOR_MAX_PCT,
    GRADE_RETURN_SCORE_EXCELLENT_MIN_PCT,
    GRADE_RETURN_SCORE_GOOD_MIN_PCT,
    GRADE_RETURN_SCORE_MODERATE_MIN_PCT,
    GRADE_RETURN_SCORE_POSITIVE_MIN_PCT,
    GRADE_SAMPLE_SCORE_LARGE_MIN_TRADES,
    GRADE_SAMPLE_SCORE_MEDIUM_MIN_TRADES,
    GRADE_SAMPLE_SCORE_SMALL_MIN_TRADES,
    GRADE_SHARPE_SCORE_EXCELLENT_MIN,
    GRADE_SHARPE_SCORE_GOOD_MIN,
    GRADE_SHARPE_SCORE_MODERATE_MIN,
    GRADE_SHARPE_SCORE_POSITIVE_MIN,
    RECOMMENDED_EXPERIENCED_MIN_TRADES_PER_MONTH,
    RECOMMENDED_INTERMEDIATE_MIN_TRADES_PER_MONTH,
    RETURN_POTENTIAL_MODERATE_MIN_PCT,
    RETURN_POTENTIAL_MODERATE_MIN_TRADES,
    RETURN_POTENTIAL_STRONG_MIN_PCT,
    RETURN_POTENTIAL_STRONG_MIN_SHARPE,
    RETURN_POTENTIAL_STRONG_MIN_TRADES,
    RISK_CONSERVATIVE_MAX_DRAWDOWN_PCT,
    RISK_CONSERVATIVE_MAX_VOLATILITY_PCT,
    RISK_CONSERVATIVE_MIN_VAR_95_PCT,
    RISK_MODERATE_MAX_DRAWDOWN_PCT,
    RISK_MODERATE_MAX_VOLATILITY_PCT,
    RISK_MODERATE_MIN_VAR_95_PCT,
)
from engine.descriptions import build_assessment_notes


def build_assessment(metrics: dict[str, Any]) -> dict[str, str]:
    """
    Derive all user-facing assessment labels and the notes description
    from the computed metrics dict.

    Returns
    -------
    dict with keys:
        overall_grade, return_potential, risk_profile,
        drawdown_tolerance_required, recommended_for, notes
    """
    total_trades        = int(metrics.get("total_trades") or 0)
    total_return_pct    = float(metrics.get("total_return_pct") or 0.0)
    sharpe_ratio        = float(metrics.get("sharpe_ratio") or 0.0)
    max_drawdown        = float(metrics.get("max_drawdown") or 0.0)
    volatility_pct      = float(metrics.get("volatility_pct") or 0.0)
    var_95_pct          = float(metrics.get("var_95_pct") or 0.0)
    # Preserve None (never recovered) — do NOT coerce to 0, which would read as
    # an instant recovery and understate the required drawdown tolerance.
    _recovery_raw       = metrics.get("recovery_time_days")
    recovery_time_days  = int(_recovery_raw) if _recovery_raw is not None else None
    trades_per_month    = float(metrics.get("trades_per_month") or 0.0)

    if total_trades <= 0:
        return {
            "overall_grade":             "D",
            "return_potential":          "Weak",
            "risk_profile":              "Conservative",
            "drawdown_tolerance_required": "Low",
            "recommended_for":           "Not Recommended",
            "notes": build_assessment_notes(
                grade="D",
                return_potential="Weak",
                risk_profile="Conservative",
                metrics=metrics,
            ),
        }

    return_potential = _classify_return_potential(
        total_return_pct=total_return_pct,
        sharpe_ratio=sharpe_ratio,
        total_trades=total_trades,
    )
    risk_profile = _classify_risk_profile(
        max_drawdown=max_drawdown,
        volatility_pct=volatility_pct,
        var_95_pct=var_95_pct,
    )
    drawdown_tolerance_required = _classify_drawdown_tolerance(
        max_drawdown=max_drawdown,
        recovery_time_days=recovery_time_days,
    )
    recommended_for = _classify_recommended_for(
        risk_profile=risk_profile,
        drawdown_tolerance_required=drawdown_tolerance_required,
        trades_per_month=trades_per_month,
        total_return_pct=total_return_pct,
        sharpe_ratio=sharpe_ratio,
    )
    overall_grade = _compute_overall_grade(metrics)

    notes = build_assessment_notes(
        grade=overall_grade,
        return_potential=return_potential,
        risk_profile=risk_profile,
        metrics=metrics,
    )

    return {
        "overall_grade":             overall_grade,
        "return_potential":          return_potential,
        "risk_profile":              risk_profile,
        "drawdown_tolerance_required": drawdown_tolerance_required,
        "recommended_for":           recommended_for,
        "notes":                     notes,
    }


# ── Classifier functions ───────────────────────────────────────────────────────

def _classify_return_potential(
    *,
    total_return_pct: float,
    sharpe_ratio: float,
    total_trades: int,
) -> str:
    if (
        total_return_pct >= RETURN_POTENTIAL_STRONG_MIN_PCT
        and sharpe_ratio  >= RETURN_POTENTIAL_STRONG_MIN_SHARPE
        and total_trades  >= RETURN_POTENTIAL_STRONG_MIN_TRADES
    ):
        return "Strong"
    if (
        total_return_pct >= RETURN_POTENTIAL_MODERATE_MIN_PCT
        and total_trades  >= RETURN_POTENTIAL_MODERATE_MIN_TRADES
    ):
        return "Moderate"
    return "Weak"


def _classify_risk_profile(
    *,
    max_drawdown: float,
    volatility_pct: float,
    var_95_pct: float,
) -> str:
    if (
        max_drawdown   <= RISK_CONSERVATIVE_MAX_DRAWDOWN_PCT
        and volatility_pct <= RISK_CONSERVATIVE_MAX_VOLATILITY_PCT
        and var_95_pct     >= RISK_CONSERVATIVE_MIN_VAR_95_PCT
    ):
        return "Conservative"
    if (
        max_drawdown   <= RISK_MODERATE_MAX_DRAWDOWN_PCT
        and volatility_pct <= RISK_MODERATE_MAX_VOLATILITY_PCT
        and var_95_pct     >= RISK_MODERATE_MIN_VAR_95_PCT
    ):
        return "Moderate"
    return "Aggressive"


def _classify_drawdown_tolerance(
    *,
    max_drawdown: float,
    recovery_time_days: int | None,
) -> str:
    # Never recovered to the prior peak within the window → highest tolerance.
    if recovery_time_days is None:
        return "High"
    if (
        max_drawdown       <= DRAWDOWN_TOLERANCE_LOW_MAX_PCT
        and recovery_time_days <= DRAWDOWN_TOLERANCE_LOW_MAX_RECOVERY_DAYS
    ):
        return "Low"
    if (
        max_drawdown       <= DRAWDOWN_TOLERANCE_MEDIUM_MAX_PCT
        and recovery_time_days <= DRAWDOWN_TOLERANCE_MEDIUM_MAX_RECOVERY_DAYS
    ):
        return "Medium"
    return "High"


def _classify_recommended_for(
    *,
    risk_profile: str,
    drawdown_tolerance_required: str,
    trades_per_month: float,
    total_return_pct: float,
    sharpe_ratio: float,
) -> str:
    if total_return_pct <= 0 or sharpe_ratio <= 0:
        return "Not Recommended"
    if (
        risk_profile == "Aggressive"
        or drawdown_tolerance_required == "High"
        or trades_per_month >= RECOMMENDED_EXPERIENCED_MIN_TRADES_PER_MONTH
    ):
        return "Experienced Traders"
    if (
        risk_profile == "Moderate"
        or drawdown_tolerance_required == "Medium"
        or trades_per_month >= RECOMMENDED_INTERMEDIATE_MIN_TRADES_PER_MONTH
    ):
        return "Intermediate Traders"
    return "Beginner Traders"


def _compute_overall_grade(metrics: dict[str, Any]) -> str:
    total_trades = int(metrics.get("total_trades") or 0)
    if total_trades <= 0:
        return "D"

    score = (
        _return_score(float(metrics.get("total_return_pct") or 0.0))
        + _sharpe_score(float(metrics.get("sharpe_ratio") or 0.0))
        + _drawdown_score(float(metrics.get("max_drawdown") or 0.0))
        + _consistency_score(
            profit_factor=float(metrics.get("profit_factor") or 0.0),
            win_rate=float(metrics.get("win_rate") or 0.0),
        )
        + _sample_size_score(total_trades)
    )

    if score >= GRADE_A_MIN_SCORE:
        return "A"
    if score >= GRADE_B_PLUS_MIN_SCORE:
        return "B+"
    if score >= GRADE_B_MIN_SCORE:
        return "B"
    if score >= GRADE_C_PLUS_MIN_SCORE:
        return "C+"
    if score >= GRADE_C_MIN_SCORE:
        return "C"
    return "D"


def _return_score(total_return_pct: float) -> int:
    if total_return_pct >= GRADE_RETURN_SCORE_EXCELLENT_MIN_PCT:
        return 30
    if total_return_pct >= GRADE_RETURN_SCORE_GOOD_MIN_PCT:
        return 24
    if total_return_pct >= GRADE_RETURN_SCORE_MODERATE_MIN_PCT:
        return 16
    if total_return_pct >= GRADE_RETURN_SCORE_POSITIVE_MIN_PCT:
        return 8
    return 0


def _sharpe_score(sharpe_ratio: float) -> int:
    if sharpe_ratio >= GRADE_SHARPE_SCORE_EXCELLENT_MIN:
        return 25
    if sharpe_ratio >= GRADE_SHARPE_SCORE_GOOD_MIN:
        return 18
    if sharpe_ratio >= GRADE_SHARPE_SCORE_MODERATE_MIN:
        return 10
    if sharpe_ratio > GRADE_SHARPE_SCORE_POSITIVE_MIN:
        return 5
    return 0


def _drawdown_score(max_drawdown: float) -> int:
    if max_drawdown <= GRADE_DRAWDOWN_SCORE_EXCELLENT_MAX_PCT:
        return 25
    if max_drawdown <= GRADE_DRAWDOWN_SCORE_GOOD_MAX_PCT:
        return 18
    if max_drawdown <= GRADE_DRAWDOWN_SCORE_MODERATE_MAX_PCT:
        return 12
    if max_drawdown <= GRADE_DRAWDOWN_SCORE_FAIR_MAX_PCT:
        return 8
    if max_drawdown <= GRADE_DRAWDOWN_SCORE_POOR_MAX_PCT:
        return 4
    return 0


def _consistency_score(*, profit_factor: float, win_rate: float) -> int:
    if (
        profit_factor >= GRADE_CONSISTENCY_SCORE_EXCELLENT_MIN_PF
        and win_rate  >= GRADE_CONSISTENCY_SCORE_EXCELLENT_MIN_WR
    ):
        return 15
    if (
        profit_factor >= GRADE_CONSISTENCY_SCORE_GOOD_MIN_PF
        and win_rate  >= GRADE_CONSISTENCY_SCORE_GOOD_MIN_WR
    ):
        return 12
    if (
        profit_factor >= GRADE_CONSISTENCY_SCORE_MODERATE_MIN_PF
        and win_rate  >= GRADE_CONSISTENCY_SCORE_MODERATE_MIN_WR
    ):
        return 8
    if profit_factor >= GRADE_CONSISTENCY_SCORE_FAIR_MIN_PF:
        return 4
    return 0


def _sample_size_score(total_trades: int) -> int:
    if total_trades >= GRADE_SAMPLE_SCORE_LARGE_MIN_TRADES:
        return 5
    if total_trades >= GRADE_SAMPLE_SCORE_MEDIUM_MIN_TRADES:
        return 4
    if total_trades >= GRADE_SAMPLE_SCORE_SMALL_MIN_TRADES:
        return 2
    return 0
