"""
Backtest metrics and result envelope builders.

Pass/fail thresholds are objective-aware (see config.PASS_FAIL_THRESHOLDS):
  intraday:   win_rate>=40%
  positional: win_rate>=40%, profit_factor>=1.2

All numeric constants are imported from config.py.
Text descriptions are generated by descriptions.py via assessment.py.
Market phase and monthly performance are built by market_classifier.py.
"""
from __future__ import annotations

import logging
from typing import Any

import pandas as pd

from engine.assessment import build_assessment
from engine.config import (
    CALENDAR_DAYS_PER_MONTH,
    DEFAULT_STARTING_BALANCE,
    PASS_FAIL_THRESHOLDS,
    PROFIT_FACTOR_MAX_CAP,
    TRADING_DAYS_PER_YEAR,
    VAR_CONFIDENCE_LEVEL,
)
from engine.market_classifier import (
    build_market_phase_analysis,
    classify_entry_condition,
    compute_monthly_performance,
)
from engine.simulator import Trade

logger = logging.getLogger(__name__)


# ── Threshold helpers ──────────────────────────────────────────────────────────

def _get_thresholds(objective: str) -> dict:
    return PASS_FAIL_THRESHOLDS.get(
        str(objective).lower(),
        PASS_FAIL_THRESHOLDS["positional"],
    )


# ── Timestamp helpers ──────────────────────────────────────────────────────────

def _parse_timestamp(value: str) -> pd.Timestamp:
    timestamp = pd.to_datetime(value, utc=True)
    if getattr(timestamp, "tzinfo", None) is not None:
        return timestamp.tz_convert("UTC").tz_localize(None)
    return timestamp.tz_localize(None)


def _round(value: float, ndigits: int = 4) -> float:
    return round(float(value), ndigits)


def _format_trade_timestamp(value: str) -> str:
    return pd.to_datetime(value, utc=True).isoformat().replace("+00:00", "Z")


def _calendar_days(start_utc: str, end_utc: str) -> int:
    start = _parse_timestamp(start_utc).normalize()
    end   = _parse_timestamp(end_utc).normalize()
    return int((end - start).days) + 1


# ── Empty / error metrics ─────────────────────────────────────────────────────

def _empty_metrics(
    *,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str | None = None,
    end_utc: str | None = None,
) -> dict:
    num_days = _calendar_days(start_utc, end_utc) if start_utc and end_utc else 0
    return {
        "num_days":                    num_days,
        "win_rate":                    0.0,
        "irr_daily":                   0.0,
        "calmar_ratio":                0.0,
        "max_drawdown":                0.0,
        "sharpe_ratio":                0.0,
        "total_trades":                0,
        "annual_return":               0.0,
        "sortino_ratio":               0.0,
        "ending_balance":              _round(starting_balance, 2),
        "irr_annualized":              0.0,
        "avg_daily_return":            0.0,
        "total_return_pct":            0.0,
        "net_return_pct":              0.0,
        "gross_return_pct":            0.0,
        "volatility_pct":              0.0,
        "downside_deviation_pct":      0.0,
        "profit_factor":               0.0,
        "var_95_pct":                  0.0,
        "expected_shortfall_95_pct":   0.0,
        "average_holding_duration":    0.0,
        "trades_per_month":            0.0,
        "longest_losing_streak":       0,
        "average_outcome_per_trade":   0.0,
        "starting_balance":            _round(starting_balance, 2),
        "max_drawdown_duration":       0,
        "worst_drawdown_start_date":   None,
        "worst_drawdown_end_date":     None,
        "drawdown_duration_days":      0,
        "recovery_date":               None,
        "recovery_time_days":          0,
        "monthly_performance":         [],
        "monthly_statistics":          {},
        "backtest_trades":             [],
    }


# ── Result envelope builders ──────────────────────────────────────────────────

def build_execution_error_result(
    *,
    backtest_ref_id: str,
    reason: str,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str | None = None,
    end_utc: str | None = None,
    config: dict | None = None,
) -> dict:
    return {
        "backtest_ref_id":       backtest_ref_id,
        "strategy_name":         None,
        "backtest_date_range":   _build_date_range(start_utc, end_utc),
        "metrics":               _empty_metrics(
                                     starting_balance=starting_balance,
                                     start_utc=start_utc,
                                     end_utc=end_utc,
                                 ),
        "assessment":            None,
        "monthly_performance":   [],
        "monthly_statistics":    {},
        "market_phase_analysis": [],
        "failure_reason":        f"Backtest execution failed: {reason}",
        "pass":                  False,
        "config":                config,
        "strategy_type":         "unknown",
        "diagnostic_summary":    {},
    }


def build_backtest_result(
    *,
    trades: list[Trade],
    df: pd.DataFrame,
    backtest_ref_id: str,
    strategy_name: str = "Unknown Strategy",
    strategy_side: str = "LONG",
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str,
    end_utc: str,
    objective: str = "positional",
    diagnostics: list[dict] | None = None,
    config: dict | None = None,
) -> dict:
    metrics = calculate_metrics(
        trades=trades,
        df=df,
        starting_balance=starting_balance,
        start_utc=start_utc,
        end_utc=end_utc,
    )
    assessment = build_assessment(metrics)

    thresholds    = _get_thresholds(objective)
    total_trades  = int(metrics["total_trades"])
    win_rate      = float(metrics["win_rate"])
    profit_factor = float(metrics["profit_factor"])
    min_win_rate  = float(thresholds["min_win_rate_pct"])
    min_pf        = float(thresholds["min_profit_factor"])

    passed = (
        total_trades  > 0
        and win_rate  >= min_win_rate
        and (min_pf <= 0.0 or profit_factor >= min_pf)
    )

    # Build human-readable failure reason
    if total_trades == 0:
        diag_hints     = _build_no_trade_hints(diagnostics or [], df)
        failure_reason = (
            f"Strategy failed: no trades were executed during the "
            f"{metrics['num_days']}-day backtest window. "
            f"Historical data loaded successfully, but the entry conditions "
            f"never triggered across {len(df)} candles. {diag_hints}"
        ).strip()
    elif win_rate < min_win_rate:
        failure_reason = (
            f"Strategy failed: win rate {win_rate:.2f}% is below the required "
            f"{min_win_rate:.0f}% threshold."
        )
    elif min_pf > 0 and profit_factor < min_pf:
        failure_reason = (
            f"Strategy failed: profit factor {profit_factor:.2f} is below the required "
            f"{min_pf:.2f} for {objective} strategies."
        )
    else:
        failure_reason = ""

    # Market phase analysis (quarters)
    market_phase_analysis = build_market_phase_analysis(df, trades, strategy_side)

    # Monthly performance + statistics (already inside metrics dict)
    monthly_performance = metrics.pop("monthly_performance", [])
    monthly_statistics  = metrics.pop("monthly_statistics", {})

    # Diagnostic summary
    diag_summary = _build_diagnostic_summary(diagnostics or [])

    result = {
        "backtest_ref_id":       backtest_ref_id,
        "strategy_name":         strategy_name,
        "backtest_date_range":   _build_date_range(start_utc, end_utc),
        "metrics":               metrics,
        "assessment":            assessment,
        "monthly_performance":   monthly_performance,
        "monthly_statistics":    monthly_statistics,
        "market_phase_analysis": market_phase_analysis,
        "failure_reason":        failure_reason,
        "pass":                  passed,
        "config":                config,
        "strategy_type":         objective,
        "diagnostic_summary":    diag_summary,
    }

    logger.info(
        "Built backtest result | ref=%s objective=%s pass=%s "
        "total_trades=%s win_rate=%.2f profit_factor=%.2f",
        backtest_ref_id, objective, passed, total_trades, win_rate, profit_factor,
    )
    return result


def _build_date_range(start_utc: str | None, end_utc: str | None) -> dict:
    if not start_utc or not end_utc:
        return {"from": None, "to": None, "num_days": 0}
    try:
        from_date = _parse_timestamp(start_utc).date().isoformat()
        to_date   = _parse_timestamp(end_utc).date().isoformat()
        num_days  = _calendar_days(start_utc, end_utc)
        return {"from": from_date, "to": to_date, "num_days": num_days}
    except Exception:
        return {"from": None, "to": None, "num_days": 0}


# ── Core metrics calculator ───────────────────────────────────────────────────

def calculate_metrics(
    *,
    trades: list[Trade],
    df: pd.DataFrame,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str,
    end_utc: str,
) -> dict:
    if df is None or df.empty:
        return _empty_metrics(
            starting_balance=starting_balance,
            start_utc=start_utc,
            end_utc=end_utc,
        )

    num_days        = _calendar_days(start_utc, end_utc)
    trade_snapshots = _trade_snapshots(trades, starting_balance)
    ending_balance  = trade_snapshots[-1]["ending_balance"] if trade_snapshots else starting_balance
    total_trades    = len(trades)
    wins            = sum(1 for t in trades if t.pnl_pct > 0)
    win_rate        = (wins / total_trades * 100.0) if total_trades else 0.0
    net_return_pct  = (
        (ending_balance - starting_balance) / starting_balance * 100.0
        if starting_balance else 0.0
    )
    gross_return_pct = sum(float(t.pnl_pct) for t in trades)
    average_outcome_per_trade = gross_return_pct / total_trades if total_trades else 0.0

    gross_profit = sum(float(t.pnl_abs) for t in trades if t.pnl_abs > 0)
    gross_loss   = abs(sum(float(t.pnl_abs) for t in trades if t.pnl_abs < 0))
    profit_factor_raw = (
        (gross_profit / gross_loss) if gross_loss > 0
        else (float("inf") if gross_profit > 0 else 0.0)
    )
    profit_factor = min(profit_factor_raw, PROFIT_FACTOR_MAX_CAP)

    annual_return = (
        (((ending_balance / starting_balance) ** (365.0 / num_days)) - 1.0) * 100.0
        if starting_balance > 0 and num_days > 0
        else 0.0
    )

    daily_values   = _daily_portfolio_values(
        df=df,
        trade_snapshots=trade_snapshots,
        starting_balance=starting_balance,
        start_utc=start_utc,
        end_utc=end_utc,
    )
    # daily_returns in decimal form (e.g. 0.01 = 1% gain)
    daily_returns     = daily_values.pct_change().fillna(0.0)
    # daily_returns_pct in percentage form (e.g. 1.0 = 1% gain)
    daily_returns_pct = daily_returns * 100.0

    avg_daily_return = float(daily_returns.mean()) * 100.0
    sharpe_ratio     = _annualized_sharpe(daily_returns)
    sortino_ratio    = _annualized_sortino(daily_returns)
    drawdown_stats   = _drawdown_stats(daily_values)
    max_drawdown             = float(drawdown_stats["max_drawdown"])
    max_drawdown_duration    = int(drawdown_stats["max_drawdown_duration"])
    worst_drawdown_start_date = drawdown_stats["worst_drawdown_start_date"]
    worst_drawdown_end_date   = drawdown_stats["worst_drawdown_end_date"]
    drawdown_duration_days    = int(drawdown_stats["drawdown_duration_days"])
    recovery_date             = drawdown_stats["recovery_date"]
    recovery_time_days        = int(drawdown_stats["recovery_time_days"])

    calmar_ratio = (annual_return / max_drawdown) if max_drawdown > 0 else 0.0

    irr_daily = (
        ((ending_balance / starting_balance) ** (1.0 / num_days) - 1.0)
        if starting_balance > 0 and ending_balance > 0 and num_days > 0
        else 0.0
    )
    irr_annualized = ((1.0 + irr_daily) ** 365 - 1.0) if irr_daily > -1.0 else -1.0

    volatility_pct              = _annualized_volatility(daily_returns_pct)
    downside_deviation_pct      = _annualized_downside_deviation(daily_returns_pct)
    var_95_pct, expected_shortfall_95_pct = _historical_var_and_expected_shortfall(
        daily_returns_pct
    )
    average_holding_duration = _avg_trade_duration_days(trades)
    trades_per_month         = _trades_per_month(total_trades, num_days)
    longest_losing_streak    = _longest_losing_streak(trades)
    rounded_average_holding_duration = _round(average_holding_duration, 4)
    rounded_average_outcome_per_trade = _round(average_outcome_per_trade)

    monthly_performance, monthly_statistics = compute_monthly_performance(
        daily_values, trades
    )

    return {
        "num_days":                    int(num_days),
        "win_rate":                    _round(win_rate),
        "irr_daily":                   _round(irr_daily),
        "calmar_ratio":                _round(calmar_ratio),
        "max_drawdown":                _round(max_drawdown),
        "sharpe_ratio":                _round(sharpe_ratio),
        "total_trades":                int(total_trades),
        "annual_return":               _round(annual_return),
        "sortino_ratio":               _round(sortino_ratio),
        "ending_balance":              _round(ending_balance, 2),
        "irr_annualized":              _round(irr_annualized),
        "avg_daily_return":            _round(avg_daily_return),
        "total_return_pct":            _round(net_return_pct),
        "net_return_pct":              _round(net_return_pct),
        "gross_return_pct":            _round(gross_return_pct),
        "volatility_pct":              _round(volatility_pct),
        "downside_deviation_pct":      _round(downside_deviation_pct),
        "profit_factor":               _round(profit_factor),
        "var_95_pct":                  _round(var_95_pct),
        "expected_shortfall_95_pct":   _round(expected_shortfall_95_pct),
        "average_holding_duration":    rounded_average_holding_duration,
        "trades_per_month":            _round(trades_per_month, 2),
        "longest_losing_streak":       int(longest_losing_streak),
        "average_outcome_per_trade":   rounded_average_outcome_per_trade,
        "starting_balance":            _round(starting_balance, 2),
        "max_drawdown_duration":       int(max_drawdown_duration),
        "worst_drawdown_start_date":   worst_drawdown_start_date,
        "worst_drawdown_end_date":     worst_drawdown_end_date,
        "drawdown_duration_days":      drawdown_duration_days,
        "recovery_date":               recovery_date,
        "recovery_time_days":          recovery_time_days,
        "monthly_performance":         monthly_performance,
        "monthly_statistics":          monthly_statistics,
        "backtest_trades":             _serialize_backtest_trades(trades, df),
    }


# ── Trade serialization ────────────────────────────────────────────────────────

def _serialize_backtest_trades(trades: list[Trade], df: pd.DataFrame) -> list[dict]:
    """
    Serialize each trade to a dict, enriched with:
      - entry_market_condition (Bull / Bear / Sideways at entry bar)
      - mae_pct (maximum adverse excursion %)
      - mfe_pct (maximum favorable excursion %)
      - holding_duration_days (calendar days between entry and exit)
    """
    sorted_trades = sorted(trades, key=lambda t: _parse_timestamp(t.entry_date))

    # Build a bar-index lookup from the DataFrame index
    df_index = df.index if df is not None and not df.empty else None

    result = []
    for trade in sorted_trades:
        # Resolve entry bar index for classify_entry_condition
        entry_condition_label = "Unknown"
        if df_index is not None:
            try:
                entry_ts  = _parse_timestamp(trade.entry_date)
                bar_idx   = int(df_index.searchsorted(entry_ts, side="left"))
                entry_condition_label = classify_entry_condition(df, bar_idx)
            except Exception:
                pass

        # Holding duration in calendar days
        try:
            entry_ts   = _parse_timestamp(trade.entry_date)
            exit_ts    = _parse_timestamp(trade.exit_date)
            hold_days  = round((exit_ts - entry_ts).total_seconds() / 86400.0, 2)
        except Exception:
            hold_days = 0.0

        result.append({
            "instrument":            str(trade.symbol),
            "entry_date":            _format_trade_timestamp(trade.entry_date),
            "exit_date":             _format_trade_timestamp(trade.exit_date),
            "side":                  str(trade.side),
            "entry_price":           _round(trade.entry_price),
            "exit_price":            _round(trade.exit_price),
            "outcome_pct":           _round(trade.pnl_pct),
            "pnl_pct":               _round(trade.pnl_pct),
            "pnl_abs":               _round(trade.pnl_abs, 6),
            "pnl_inr":               _round(getattr(trade, "pnl_inr", 0.0), 4),
            "exit_reason":           str(trade.exit_reason),
            "holding_candles":       int(trade.holding_candles),
            "holding_duration_days": hold_days,
            "entry_market_condition": entry_condition_label,
            "max_adverse_excursion_pct":  _round(getattr(trade, "mae_pct", 0.0)),
            "max_favorable_excursion_pct": _round(getattr(trade, "mfe_pct", 0.0)),
        })
    return result


# ── Portfolio helpers ─────────────────────────────────────────────────────────

def _trade_snapshots(trades: list[Trade], starting_balance: float) -> list[dict]:
    snapshots: list[dict] = []
    balance = float(starting_balance)

    for trade in sorted(trades, key=lambda t: _parse_timestamp(t.entry_date)):
        pnl_value      = balance * float(trade.pnl_abs)
        ending_balance = balance + pnl_value
        snapshots.append({
            "entry_ts":         _parse_timestamp(trade.entry_date),
            "exit_ts":          _parse_timestamp(trade.exit_date),
            "entry_price":      float(trade.entry_price),
            "starting_balance": balance,
            "ending_balance":   ending_balance,
        })
        balance = ending_balance

    return snapshots


def _daily_portfolio_values(
    *,
    df: pd.DataFrame,
    trade_snapshots: list[dict],
    starting_balance: float,
    start_utc: str,
    end_utc: str,
) -> pd.Series:
    start_day = _parse_timestamp(start_utc).normalize()
    end_day   = _parse_timestamp(end_utc).normalize()
    full_days = pd.date_range(start_day, end_day, freq="D")

    portfolio = pd.Series(index=df.index, dtype=float)
    cursor    = 0
    balance   = float(starting_balance)

    for snapshot in trade_snapshots:
        entry_idx = int(df.index.searchsorted(snapshot["entry_ts"], side="left"))
        exit_idx  = int(df.index.searchsorted(snapshot["exit_ts"],  side="right"))

        if entry_idx > cursor:
            portfolio.iloc[cursor:entry_idx] = balance

        trade_slice = df["close"].iloc[entry_idx:exit_idx].astype(float)
        if not trade_slice.empty:
            portfolio.iloc[entry_idx:exit_idx] = snapshot["starting_balance"] * (
                trade_slice / snapshot["entry_price"]
            )

        balance = float(snapshot["ending_balance"])
        cursor  = exit_idx

    if cursor < len(portfolio):
        portfolio.iloc[cursor:] = balance

    portfolio    = portfolio.ffill().fillna(float(starting_balance))
    daily_values = portfolio.resample("D").last().ffill()
    daily_values = (
        daily_values
        .reindex(full_days, method="ffill")
        .fillna(float(starting_balance))
    )
    return daily_values.astype(float)


# ── Drawdown analysis ─────────────────────────────────────────────────────────

def _drawdown_stats(portfolio_values: pd.Series) -> dict[str, Any]:
    """
    Always returns a dict with all drawdown fields.
    Finds the worst peak-to-trough drawdown, its dates, duration, and recovery.
    """
    empty: dict[str, Any] = {
        "max_drawdown":            0.0,
        "max_drawdown_duration":   0,
        "worst_drawdown_start_date": None,
        "worst_drawdown_end_date":   None,
        "drawdown_duration_days":  0,
        "recovery_date":           None,
        "recovery_time_days":      0,
    }

    if portfolio_values is None or portfolio_values.empty:
        return empty

    running_peak = portfolio_values.cummax()
    drawdowns    = ((portfolio_values / running_peak) - 1.0) * 100.0
    max_drawdown = abs(float(drawdowns.min())) if not drawdowns.empty else 0.0

    if max_drawdown <= 0.0:
        return empty

    # Index of worst trough
    trough_idx = drawdowns.idxmin()
    # Peak before the trough
    peak_idx   = portfolio_values.loc[:trough_idx].idxmax()
    peak_value = float(portfolio_values.loc[peak_idx])

    # First date after trough where portfolio recovers to peak value
    after_trough     = portfolio_values.loc[trough_idx:]
    recovery_series  = after_trough[after_trough >= peak_value]
    recovery_idx     = recovery_series.index[0] if not recovery_series.empty else None

    # Worst drawdown duration: calendar days from peak to trough
    try:
        dd_duration_days = int((trough_idx - peak_idx).days)
    except Exception:
        dd_duration_days = 0

    # Recovery time: calendar days from trough to recovery
    try:
        recovery_time = int((recovery_idx - trough_idx).days) if recovery_idx is not None else 0
    except Exception:
        recovery_time = 0

    # Max consecutive days spent underwater (below any prior peak)
    underwater        = drawdowns < 0
    max_underwater    = 0
    current_streak    = 0
    for is_under in underwater:
        if is_under:
            current_streak += 1
            max_underwater  = max(max_underwater, current_streak)
        else:
            current_streak  = 0

    return {
        "max_drawdown":            max_drawdown,
        "max_drawdown_duration":   max_underwater,
        "worst_drawdown_start_date": str(peak_idx.date())     if peak_idx is not None else None,
        "worst_drawdown_end_date":   str(trough_idx.date())   if trough_idx is not None else None,
        "drawdown_duration_days":  dd_duration_days,
        "recovery_date":           str(recovery_idx.date())   if recovery_idx is not None else None,
        "recovery_time_days":      recovery_time,
    }


# ── Statistical helpers ────────────────────────────────────────────────────────

def _annualized_sharpe(daily_returns: pd.Series) -> float:
    """Annualized Sharpe ratio (risk-free rate = 0). daily_returns in decimal form."""
    std_dev = float(daily_returns.std(ddof=1)) if len(daily_returns) > 1 else 0.0
    if std_dev <= 0:
        return 0.0
    return float((daily_returns.mean() / std_dev) * (TRADING_DAYS_PER_YEAR ** 0.5))


def _annualized_sortino(daily_returns: pd.Series) -> float:
    """Annualized Sortino ratio. daily_returns in decimal form."""
    downside     = daily_returns[daily_returns < 0]
    downside_std = float(downside.std(ddof=1)) if len(downside) > 1 else 0.0
    if downside_std <= 0:
        return 0.0
    return float((daily_returns.mean() / downside_std) * (TRADING_DAYS_PER_YEAR ** 0.5))


def _annualized_volatility(daily_returns_pct: pd.Series) -> float:
    """Annualized standard deviation of daily returns (in %)."""
    if len(daily_returns_pct) < 2:
        return 0.0
    return float(daily_returns_pct.std(ddof=1)) * (TRADING_DAYS_PER_YEAR ** 0.5)


def _annualized_downside_deviation(daily_returns_pct: pd.Series) -> float:
    """Annualized std dev of only the negative daily returns (in %)."""
    downside = daily_returns_pct[daily_returns_pct < 0]
    if len(downside) < 2:
        return 0.0
    return float(downside.std(ddof=1)) * (TRADING_DAYS_PER_YEAR ** 0.5)


def _historical_var_and_expected_shortfall(
    daily_returns_pct: pd.Series,
) -> tuple[float, float]:
    """
    Historical VaR at VAR_CONFIDENCE_LEVEL and Expected Shortfall (CVaR).
    Both returned as negative numbers indicating potential loss (in %).
    """
    if daily_returns_pct.empty:
        return 0.0, 0.0
    sorted_returns = daily_returns_pct.sort_values()
    cutoff_idx     = max(1, int(len(sorted_returns) * VAR_CONFIDENCE_LEVEL))
    var_95         = float(sorted_returns.iloc[cutoff_idx - 1])
    tail           = sorted_returns.iloc[:cutoff_idx]
    es_95          = float(tail.mean()) if not tail.empty else 0.0
    return _round(var_95), _round(es_95)


def _avg_trade_duration_days(trades: list[Trade]) -> float:
    """Mean calendar days between entry and exit across all trades."""
    if not trades:
        return 0.0
    durations = []
    for trade in trades:
        try:
            entry    = _parse_timestamp(trade.entry_date)
            exit_    = _parse_timestamp(trade.exit_date)
            duration = max(0.0, (exit_ - entry).total_seconds() / 86_400.0)
            durations.append(duration)
        except Exception:
            pass
    return float(sum(durations) / len(durations)) if durations else 0.0


def _trades_per_month(total_trades: int, num_days: int) -> float:
    """Average number of trades per calendar month."""
    if num_days <= 0:
        return 0.0
    return total_trades / (num_days / CALENDAR_DAYS_PER_MONTH)


def _longest_losing_streak(trades: list[Trade]) -> int:
    """Longest consecutive sequence of losing trades (pnl_pct ≤ 0)."""
    if not trades:
        return 0
    sorted_trades  = sorted(trades, key=lambda t: _parse_timestamp(t.entry_date))
    max_streak     = 0
    current_streak = 0
    for trade in sorted_trades:
        if float(trade.pnl_pct) <= 0:
            current_streak += 1
            max_streak      = max(max_streak, current_streak)
        else:
            current_streak  = 0
    return max_streak


# ── Diagnostic helpers ────────────────────────────────────────────────────────

def _build_no_trade_hints(diagnostics: list[dict], df: pd.DataFrame) -> str:
    if not diagnostics:
        return ""

    total           = len(diagnostics)
    entry_evaluated = sum(1 for d in diagnostics if d.get("entry_evaluated"))
    entry_signals   = sum(1 for d in diagnostics if d.get("entry_signal"))

    if entry_evaluated == 0:
        return (
            f"All {total} candles were consumed by indicator warm-up. "
            "Fetch more historical data so indicators are ready before the evaluation window."
        )
    if entry_signals == 0:
        return (
            f"Entry conditions were evaluated on {entry_evaluated} of {total} candles "
            "but never returned True. Check that your entry condition logic is correct "
            "and that the indicators are generating valid values."
        )
    return (
        f"Entry conditions fired {entry_signals} time(s) across {entry_evaluated} "
        "eligible candles but were blocked by circuit-breakers (daily cap / max trades)."
    )


def _build_diagnostic_summary(diagnostics: list[dict]) -> dict:
    if not diagnostics:
        return {}
    return {
        "total_candles":     len(diagnostics),
        "entry_evaluated":   sum(1 for d in diagnostics if d.get("entry_evaluated")),
        "entry_signals":     sum(1 for d in diagnostics if d.get("entry_signal")),
        "daily_cap_blocks":  sum(1 for d in diagnostics if d.get("entry_blocked_daily_cap")),
        "max_trades_blocks": sum(1 for d in diagnostics if d.get("entry_blocked_max_trades")),
        "exit_signals":      sum(1 for d in diagnostics if d.get("exit_signal")),
        "stop_hits":         sum(1 for d in diagnostics if d.get("stop_hit")),
        "tp_hits":           sum(1 for d in diagnostics if d.get("tp_hit")),
    }
