"""
Backtest metrics and result envelope builders.

Pass/fail thresholds are objective-aware (see config.PASS_FAIL_THRESHOLDS):
  intraday:   win_rate>=40%
  positional: win_rate>=40%, profit_factor>=1.2

All numeric constants are imported from config.py.
Text descriptions are generated by descriptions.py via assessment.py.
Market phase and monthly performance are built by market_classifier.py.
"""
from __future__ import annotations

import logging
import time
from typing import Any

import numpy as np
import pandas as pd

from engine.assessment import build_assessment
from engine.config import (
    CALENDAR_DAYS_PER_MONTH,
    DEFAULT_STARTING_BALANCE,
    PASS_FAIL_THRESHOLDS,
    PROFIT_FACTOR_MAX_CAP,
    TRADING_DAYS_PER_YEAR,
    VAR_CONFIDENCE_LEVEL,
)
from engine.market_classifier import (
    build_market_phase_analysis,
    compute_monthly_performance,
)
from engine.simulator import Trade

logger = logging.getLogger(__name__)


# ── Threshold helpers ──────────────────────────────────────────────────────────

def _get_thresholds(objective: str) -> dict:
    return PASS_FAIL_THRESHOLDS.get(
        str(objective).lower(),
        PASS_FAIL_THRESHOLDS["positional"],
    )


# ── Timestamp helpers ──────────────────────────────────────────────────────────

def _parse_timestamp(value: str) -> pd.Timestamp:
    timestamp = pd.to_datetime(value, utc=True)
    if getattr(timestamp, "tzinfo", None) is not None:
        return timestamp.tz_convert("UTC").tz_localize(None)
    return timestamp.tz_localize(None)


def _parse_timestamps(values: list[Any]) -> pd.DatetimeIndex:
    """Vectorized counterpart to _parse_timestamp.

    pd.to_datetime() is ~100× faster when given the whole list than when
    called per-string. We use this at the entrance to calculate_metrics so the
    downstream hot loops can consume datetime64 arrays instead of re-parsing
    the same strings tens of thousands of times.
    """
    idx = pd.to_datetime(list(values), utc=True)
    if getattr(idx, "tz", None) is not None:
        idx = idx.tz_convert("UTC").tz_localize(None)
    return idx


def _round(value: float, ndigits: int = 4) -> float:
    return round(float(value), ndigits)


def _format_trade_timestamp(value: str) -> str:
    return pd.to_datetime(value, utc=True).isoformat().replace("+00:00", "Z")


def _calendar_days(start_utc: str, end_utc: str) -> int:
    start = _parse_timestamp(start_utc).normalize()
    end   = _parse_timestamp(end_utc).normalize()
    return int((end - start).days) + 1


# ── Empty / error metrics ─────────────────────────────────────────────────────

def _empty_metrics(
    *,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str | None = None,
    end_utc: str | None = None,
) -> dict:
    num_days = _calendar_days(start_utc, end_utc) if start_utc and end_utc else 0
    return {
        "num_days":                    num_days,
        "win_rate":                    0.0,
        "irr_daily":                   0.0,
        "calmar_ratio":                0.0,
        "max_drawdown":                0.0,
        "sharpe_ratio":                0.0,
        "total_trades":                0,
        "annual_return":               0.0,
        "sortino_ratio":               0.0,
        "ending_balance":              _round(starting_balance, 2),
        "irr_annualized":              0.0,
        "avg_daily_return":            0.0,
        "total_return_pct":            0.0,
        "net_return_pct":              0.0,
        "gross_return_pct":            0.0,
        "volatility_pct":              0.0,
        "downside_deviation_pct":      0.0,
        "profit_factor":               0.0,
        "var_95_pct":                  0.0,
        "expected_shortfall_95_pct":   0.0,
        "average_holding_duration":    0.0,
        "trades_per_month":            0.0,
        "longest_losing_streak":       0,
        "average_outcome_per_trade":   0.0,
        "starting_balance":            _round(starting_balance, 2),
        "max_drawdown_duration":       0,
        "worst_drawdown_start_date":   None,
        "worst_drawdown_end_date":     None,
        "drawdown_duration_days":      0,
        "recovery_date":               None,
        "recovery_time_days":          0,
        "monthly_performance":         [],
        "monthly_statistics":          {},
        "backtest_trades":             [],
    }


# ── Result envelope builders ──────────────────────────────────────────────────

def build_execution_error_result(
    *,
    backtest_ref_id: str,
    reason: str,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str | None = None,
    end_utc: str | None = None,
    config: dict | None = None,
) -> dict:
    return {
        "backtest_ref_id":       backtest_ref_id,
        "strategy_name":         None,
        "backtest_date_range":   _build_date_range(start_utc, end_utc),
        "metrics":               _empty_metrics(
                                     starting_balance=starting_balance,
                                     start_utc=start_utc,
                                     end_utc=end_utc,
                                 ),
        "assessment":            None,
        "monthly_performance":   [],
        "monthly_statistics":    {},
        "market_phase_analysis": [],
        "failure_reason":        f"Backtest execution failed: {reason}",
        "pass":                  False,
        "config":                config,
        "strategy_type":         "unknown",
        "diagnostic_summary":    {},
    }


def build_backtest_result(
    *,
    trades: list[Trade],
    df: pd.DataFrame,
    backtest_ref_id: str,
    strategy_name: str = "Unknown Strategy",
    strategy_side: str = "LONG",
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str,
    end_utc: str,
    objective: str = "positional",
    diagnostics: list[dict] | None = None,
    config: dict | None = None,
) -> dict:
    _t = time.perf_counter()
    metrics = calculate_metrics(
        trades=trades,
        df=df,
        starting_balance=starting_balance,
        start_utc=start_utc,
        end_utc=end_utc,
    )
    logger.info(
        "⏱️  TIMING|step=calculate_metrics|duration=%.4fs|trades=%d|candles=%d",
        time.perf_counter() - _t, len(trades), len(df) if df is not None else 0,
    )

    _t = time.perf_counter()
    assessment = build_assessment(metrics)
    logger.info(
        "⏱️  TIMING|step=build_assessment|duration=%.4fs",
        time.perf_counter() - _t,
    )

    thresholds    = _get_thresholds(objective)
    total_trades  = int(metrics["total_trades"])
    win_rate      = float(metrics["win_rate"])
    profit_factor = float(metrics["profit_factor"])
    min_win_rate  = float(thresholds["min_win_rate_pct"])
    min_pf        = float(thresholds["min_profit_factor"])

    passed = (
        total_trades  > 0
        and win_rate  >= min_win_rate
        and (min_pf <= 0.0 or profit_factor >= min_pf)
    )

    # Build human-readable failure reason
    if total_trades == 0:
        diag_hints     = _build_no_trade_hints(diagnostics or [], df)
        # Don't claim entries "never triggered" when they did — the diag hint
        # carries the precise cause (e.g. a gate blocked every fill).
        any_entry_signal = any(d.get("entry_signal") for d in (diagnostics or []))
        lead = (
            "Historical data loaded successfully, but no entry produced a trade"
            if any_entry_signal
            else "Historical data loaded successfully, but the entry conditions "
                 f"never triggered across {len(df)} candles"
        )
        failure_reason = (
            f"Strategy failed: no trades were executed during the "
            f"{metrics['num_days']}-day backtest window. {lead}. {diag_hints}"
        ).strip()
    elif win_rate < min_win_rate:
        failure_reason = (
            f"Strategy failed: win rate {win_rate:.2f}% is below the required "
            f"{min_win_rate:.0f}% threshold."
        )
    elif min_pf > 0 and profit_factor < min_pf:
        failure_reason = (
            f"Strategy failed: profit factor {profit_factor:.2f} is below the required "
            f"{min_pf:.2f} for {objective} strategies."
        )
    else:
        failure_reason = ""

    # Market phase analysis (quarters). The classifier needs the trade entry
    # timestamps in DatetimeIndex form; share the same batch parse so we don't
    # re-walk all entry strings here.
    _t = time.perf_counter()
    entry_ts_for_phase = (
        _parse_timestamps([t.entry_date for t in trades]) if trades else pd.DatetimeIndex([])
    )
    market_phase_analysis = build_market_phase_analysis(
        df, trades, strategy_side, entry_ts_sorted=entry_ts_for_phase,
    )
    logger.info(
        "⏱️  TIMING|step=build_market_phase_analysis|duration=%.4fs|phases=%d",
        time.perf_counter() - _t, len(market_phase_analysis),
    )

    # Monthly performance + statistics (already inside metrics dict)
    monthly_performance = metrics.pop("monthly_performance", [])
    monthly_statistics  = metrics.pop("monthly_statistics", {})

    # Diagnostic summary
    _t = time.perf_counter()
    diag_summary = _build_diagnostic_summary(diagnostics or [])
    logger.info(
        "⏱️  TIMING|step=build_diagnostic_summary|duration=%.4fs",
        time.perf_counter() - _t,
    )

    result = {
        "backtest_ref_id":       backtest_ref_id,
        "strategy_name":         strategy_name,
        "backtest_date_range":   _build_date_range(start_utc, end_utc),
        "metrics":               metrics,
        "assessment":            assessment,
        "monthly_performance":   monthly_performance,
        "monthly_statistics":    monthly_statistics,
        "market_phase_analysis": market_phase_analysis,
        "failure_reason":        failure_reason,
        "pass":                  passed,
        "config":                config,
        "strategy_type":         objective,
        "diagnostic_summary":    diag_summary,
    }

    logger.info(
        "Built backtest result | ref=%s objective=%s pass=%s "
        "total_trades=%s win_rate=%.2f profit_factor=%.2f",
        backtest_ref_id, objective, passed, total_trades, win_rate, profit_factor,
    )
    return result


def _build_date_range(start_utc: str | None, end_utc: str | None) -> dict:
    if not start_utc or not end_utc:
        return {"from": None, "to": None, "num_days": 0}
    try:
        from_date = _parse_timestamp(start_utc).date().isoformat()
        to_date   = _parse_timestamp(end_utc).date().isoformat()
        num_days  = _calendar_days(start_utc, end_utc)
        return {"from": from_date, "to": to_date, "num_days": num_days}
    except Exception:
        return {"from": None, "to": None, "num_days": 0}


# ── Core metrics calculator ───────────────────────────────────────────────────

def calculate_metrics(
    *,
    trades: list[Trade],
    df: pd.DataFrame,
    starting_balance: float = DEFAULT_STARTING_BALANCE,
    start_utc: str,
    end_utc: str,
) -> dict:
    if df is None or df.empty:
        return _empty_metrics(
            starting_balance=starting_balance,
            start_utc=start_utc,
            end_utc=end_utc,
        )

    num_days        = _calendar_days(start_utc, end_utc)

    # One-shot batch parse of every trade entry/exit timestamp. The previous
    # code re-parsed these strings via pd.to_datetime per call inside the hot
    # loops (~7× len(trades) calls); doing it once here is ~100× faster.
    _t = time.perf_counter()
    entry_ts_all = _parse_timestamps([t.entry_date for t in trades]) if trades else pd.DatetimeIndex([])
    exit_ts_all  = _parse_timestamps([t.exit_date  for t in trades]) if trades else pd.DatetimeIndex([])
    sort_order   = entry_ts_all.argsort()
    trades_sorted   = [trades[i] for i in sort_order]
    entry_ts_sorted = entry_ts_all[sort_order]
    exit_ts_sorted  = exit_ts_all[sort_order]
    logger.info(
        "⏱️  TIMING|step=parse_and_sort_trade_timestamps|duration=%.4fs|trades=%d",
        time.perf_counter() - _t, len(trades),
    )

    _t = time.perf_counter()
    trade_snapshots = _trade_snapshots(
        trades_sorted, entry_ts_sorted, exit_ts_sorted, starting_balance,
    )
    logger.info(
        "⏱️  TIMING|step=trade_snapshots|duration=%.4fs|trades=%d",
        time.perf_counter() - _t, len(trades),
    )
    ending_balance  = trade_snapshots[-1]["ending_balance"] if trade_snapshots else starting_balance
    total_trades    = len(trades)
    wins            = sum(1 for t in trades if t.pnl_pct > 0)
    win_rate        = (wins / total_trades * 100.0) if total_trades else 0.0
    net_return_pct  = (
        (ending_balance - starting_balance) / starting_balance * 100.0
        if starting_balance else 0.0
    )
    gross_return_pct = sum(float(t.pnl_pct) for t in trades)
    average_outcome_per_trade = gross_return_pct / total_trades if total_trades else 0.0

    gross_profit = sum(float(t.pnl_abs) for t in trades if t.pnl_abs > 0)
    gross_loss   = abs(sum(float(t.pnl_abs) for t in trades if t.pnl_abs < 0))
    profit_factor_raw = (
        (gross_profit / gross_loss) if gross_loss > 0
        else (float("inf") if gross_profit > 0 else 0.0)
    )
    profit_factor = min(profit_factor_raw, PROFIT_FACTOR_MAX_CAP)

    annual_return = (
        (((ending_balance / starting_balance) ** (365.0 / num_days)) - 1.0) * 100.0
        if starting_balance > 0 and num_days > 0
        else 0.0
    )

    _t = time.perf_counter()
    daily_values   = _daily_portfolio_values(
        df=df,
        trade_snapshots=trade_snapshots,
        starting_balance=starting_balance,
        start_utc=start_utc,
        end_utc=end_utc,
    )
    logger.info(
        "⏱️  TIMING|step=daily_portfolio_values|duration=%.4fs|candles=%d|trades=%d|daily_rows=%d",
        time.perf_counter() - _t, len(df), len(trade_snapshots), len(daily_values),
    )
    # daily_returns in decimal form (e.g. 0.01 = 1% gain)
    daily_returns     = daily_values.pct_change().fillna(0.0)
    # daily_returns_pct in percentage form (e.g. 1.0 = 1% gain)
    daily_returns_pct = daily_returns * 100.0

    avg_daily_return = float(daily_returns.mean()) * 100.0
    sharpe_ratio     = _annualized_sharpe(daily_returns)
    sortino_ratio    = _annualized_sortino(daily_returns)
    drawdown_stats   = _drawdown_stats(daily_values)
    max_drawdown             = float(drawdown_stats["max_drawdown"])
    max_drawdown_duration    = int(drawdown_stats["max_drawdown_duration"])
    worst_drawdown_start_date = drawdown_stats["worst_drawdown_start_date"]
    worst_drawdown_end_date   = drawdown_stats["worst_drawdown_end_date"]
    drawdown_duration_days    = int(drawdown_stats["drawdown_duration_days"])
    recovery_date             = drawdown_stats["recovery_date"]
    # None (never recovered) is preserved as-is — not coerced to 0.
    _recovery_time            = drawdown_stats["recovery_time_days"]
    recovery_time_days        = int(_recovery_time) if _recovery_time is not None else None

    calmar_ratio = (annual_return / max_drawdown) if max_drawdown > 0 else 0.0

    irr_daily = (
        ((ending_balance / starting_balance) ** (1.0 / num_days) - 1.0)
        if starting_balance > 0 and ending_balance > 0 and num_days > 0
        else 0.0
    )
    irr_annualized = ((1.0 + irr_daily) ** 365 - 1.0) if irr_daily > -1.0 else -1.0

    volatility_pct              = _annualized_volatility(daily_returns_pct)
    downside_deviation_pct      = _annualized_downside_deviation(daily_returns_pct)
    var_95_pct, expected_shortfall_95_pct = _historical_var_and_expected_shortfall(
        daily_returns_pct
    )
    average_holding_duration = _avg_trade_duration_days(entry_ts_sorted, exit_ts_sorted)
    trades_per_month         = _trades_per_month(total_trades, num_days)
    longest_losing_streak    = _longest_losing_streak(trades_sorted)
    rounded_average_holding_duration = _round(average_holding_duration, 4)
    rounded_average_outcome_per_trade = _round(average_outcome_per_trade)

    _t = time.perf_counter()
    monthly_performance, monthly_statistics = compute_monthly_performance(
        daily_values, trades, entry_ts_sorted=entry_ts_sorted, df=df,
    )
    logger.info(
        "⏱️  TIMING|step=compute_monthly_performance|duration=%.4fs|months=%d",
        time.perf_counter() - _t, len(monthly_performance),
    )

    _t = time.perf_counter()
    serialized_trades = _serialize_backtest_trades(
        trades_sorted, entry_ts_sorted, exit_ts_sorted, df,
    )
    logger.info(
        "⏱️  TIMING|step=serialize_backtest_trades|duration=%.4fs|trades=%d|candles=%d",
        time.perf_counter() - _t, len(trades), len(df),
    )

    return {
        "num_days":                    int(num_days),
        "win_rate":                    _round(win_rate),
        "irr_daily":                   _round(irr_daily),
        "calmar_ratio":                _round(calmar_ratio),
        "max_drawdown":                _round(max_drawdown),
        "sharpe_ratio":                _round(sharpe_ratio),
        "total_trades":                int(total_trades),
        "annual_return":               _round(annual_return),
        "sortino_ratio":               _round(sortino_ratio),
        "ending_balance":              _round(ending_balance, 2),
        "irr_annualized":              _round(irr_annualized),
        "avg_daily_return":            _round(avg_daily_return),
        "total_return_pct":            _round(net_return_pct),
        "net_return_pct":              _round(net_return_pct),
        "gross_return_pct":            _round(gross_return_pct),
        "volatility_pct":              _round(volatility_pct),
        "downside_deviation_pct":      _round(downside_deviation_pct),
        "profit_factor":               _round(profit_factor),
        "var_95_pct":                  _round(var_95_pct),
        "expected_shortfall_95_pct":   _round(expected_shortfall_95_pct),
        "average_holding_duration":    rounded_average_holding_duration,
        "trades_per_month":            _round(trades_per_month, 2),
        "longest_losing_streak":       int(longest_losing_streak),
        "average_outcome_per_trade":   rounded_average_outcome_per_trade,
        "starting_balance":            _round(starting_balance, 2),
        "max_drawdown_duration":       int(max_drawdown_duration),
        "worst_drawdown_start_date":   worst_drawdown_start_date,
        "worst_drawdown_end_date":     worst_drawdown_end_date,
        "drawdown_duration_days":      drawdown_duration_days,
        "recovery_date":               recovery_date,
        "recovery_time_days":          recovery_time_days,
        "monthly_performance":         monthly_performance,
        "monthly_statistics":          monthly_statistics,
        "backtest_trades":             serialized_trades,
    }


# ── Trade serialization ────────────────────────────────────────────────────────

def _serialize_backtest_trades(
    trades_sorted: list[Trade],
    entry_ts_sorted: pd.DatetimeIndex,
    exit_ts_sorted: pd.DatetimeIndex,
    df: pd.DataFrame,
) -> list[dict]:
    """Serialize each trade to a dict with entry-bar market condition + MAE/MFE.

    Vectorized rewrite. Caller supplies trades already sorted by entry_ts plus
    the matching parsed timestamp arrays, so we avoid ~4× len(trades)
    `pd.to_datetime` calls. classify_entry_condition's rolling means are
    precomputed once over the whole close series, then looked up by bar index.
    """
    from engine.config import ENTRY_CONDITION_FAST_WINDOW, ENTRY_CONDITION_SLOW_WINDOW

    n = len(trades_sorted)
    if n == 0:
        return []

    # Entry-bar market condition labels — vectorized lookup.
    labels: list[str] = ["Unknown"] * n
    if df is not None and not df.empty:
        close_series = df["close"]
        fast_avg_arr = close_series.rolling(ENTRY_CONDITION_FAST_WINDOW).mean().to_numpy(dtype=float)
        slow_avg_arr = close_series.rolling(ENTRY_CONDITION_SLOW_WINDOW).mean().to_numpy(dtype=float)
        close_arr    = close_series.to_numpy(dtype=float)
        bar_idx_arr  = np.asarray(df.index.searchsorted(entry_ts_sorted, side="left"), dtype=np.int64)

        valid_mask = (
            (bar_idx_arr >= ENTRY_CONDITION_SLOW_WINDOW)
            & (bar_idx_arr < len(close_arr))
        )
        for i in range(n):
            if not valid_mask[i]:
                continue
            bi = int(bar_idx_arr[i])
            cur = close_arr[bi]
            f   = fast_avg_arr[bi]
            s   = slow_avg_arr[bi]
            if not (np.isfinite(cur) and np.isfinite(f) and np.isfinite(s)):
                continue
            if cur > f > s:
                labels[i] = "Bull"
            elif cur < f < s:
                labels[i] = "Bear"
            else:
                labels[i] = "Sideways"

    # Holding duration in calendar days — vectorized.
    hold_secs = (
        exit_ts_sorted.asi8 - entry_ts_sorted.asi8
    ).astype(np.float64) / 1e9  # ns → s
    hold_days_arr = hold_secs / 86400.0

    # ISO timestamps for output — formatted from the already-parsed arrays
    # (UTC, naive after parse) so we don't re-call pd.to_datetime per trade.
    entry_iso = [ts.isoformat() + "Z" for ts in entry_ts_sorted]
    exit_iso  = [ts.isoformat() + "Z" for ts in exit_ts_sorted]

    result: list[dict] = []
    for i, trade in enumerate(trades_sorted):
        result.append({
            "instrument":            str(trade.symbol),
            "entry_date":            entry_iso[i],
            "exit_date":             exit_iso[i],
            "side":                  str(trade.side),
            "entry_price":           _round(trade.entry_price),
            "exit_price":            _round(trade.exit_price),
            "outcome_pct":           _round(trade.pnl_pct),
            "pnl_pct":               _round(trade.pnl_pct),
            "pnl_abs":               _round(trade.pnl_abs, 6),
            "pnl_inr":               _round(getattr(trade, "pnl_inr", 0.0), 4),
            "exit_reason":           str(trade.exit_reason),
            "holding_candles":       int(trade.holding_candles),
            "holding_duration_days": round(float(hold_days_arr[i]), 2),
            "entry_market_condition": labels[i],
            "max_adverse_excursion_pct":  _round(getattr(trade, "mae_pct", 0.0)),
            "max_favorable_excursion_pct": _round(getattr(trade, "mfe_pct", 0.0)),
            # Structured rationale captured by the simulator: the full "why" of
            # each entry and exit (matched bar, indicator values, prices, costs).
            "entry_reason":          getattr(trade, "entry_reason", None),
            "exit_reason_detail":    getattr(trade, "exit_reason_detail", None),
            # Multi-TP: per-rung partial exit records. Empty tuple for standard trades.
            "partial_exits":         list(getattr(trade, "partial_exits", ())),
        })
    return result


# ── Portfolio helpers ─────────────────────────────────────────────────────────

def _trade_snapshots(
    trades_sorted: list[Trade],
    entry_ts_sorted: pd.DatetimeIndex,
    exit_ts_sorted: pd.DatetimeIndex,
    starting_balance: float,
) -> list[dict]:
    """Build per-trade balance snapshots without re-parsing any timestamp.

    Caller has already batch-parsed entry/exit timestamps and sorted everything
    by entry_ts. We just walk the parallel arrays, compute the running balance
    with one cumprod, and emit dicts.
    """
    n = len(trades_sorted)
    if n == 0:
        return []

    pnl_abs_arr     = np.fromiter((float(t.pnl_abs) for t in trades_sorted), dtype=float, count=n)
    entry_price_arr = np.fromiter((float(t.entry_price) for t in trades_sorted), dtype=float, count=n)
    # balance[i+1] = balance[i] * (1 + pnl_abs_arr[i]) — same recurrence as the
    # original Python loop; cumprod expresses it in one numpy call.
    growth          = 1.0 + pnl_abs_arr
    end_balances    = float(starting_balance) * np.cumprod(growth)
    start_balances  = np.empty(n, dtype=float)
    start_balances[0]  = float(starting_balance)
    start_balances[1:] = end_balances[:-1]

    snapshots: list[dict] = [
        {
            "entry_ts":         entry_ts_sorted[i],
            "exit_ts":          exit_ts_sorted[i],
            "entry_price":      float(entry_price_arr[i]),
            "starting_balance": float(start_balances[i]),
            "ending_balance":   float(end_balances[i]),
        }
        for i in range(n)
    ]
    return snapshots


def _daily_portfolio_values(
    *,
    df: pd.DataFrame,
    trade_snapshots: list[dict],
    starting_balance: float,
    start_utc: str,
    end_utc: str,
) -> pd.Series:
    """Per-candle portfolio value series, resampled to daily.

    Hot path: was a 13 k-iteration loop of pandas iloc setitems on a 1.26 M-row
    Series (~48s). We now operate on a numpy buffer instead: the searchsorted is
    bulk-vectorized, gap-fills between trades are scalar numpy slice writes
    (in-C), in-trade fills are a single numpy vector op. The Python loop still
    runs once per trade but each iteration is now O(slice) numpy work with no
    pandas overhead.
    """
    start_day = _parse_timestamp(start_utc).normalize()
    end_day   = _parse_timestamp(end_utc).normalize()
    full_days = pd.date_range(start_day, end_day, freq="D")

    n_candles = len(df)
    if n_candles == 0:
        return pd.Series(float(starting_balance), index=full_days, dtype=float)

    close_arr = df["close"].to_numpy(dtype=float)
    pos       = np.empty(n_candles, dtype=float)

    # Bulk-resolve entry/exit bar indices in one vectorized searchsorted each.
    if trade_snapshots:
        entry_ts_idx = pd.DatetimeIndex([s["entry_ts"] for s in trade_snapshots])
        exit_ts_idx  = pd.DatetimeIndex([s["exit_ts"]  for s in trade_snapshots])
        entry_idx_arr = np.asarray(df.index.searchsorted(entry_ts_idx, side="left"),  dtype=np.int64)
        exit_idx_arr  = np.asarray(df.index.searchsorted(exit_ts_idx,  side="right"), dtype=np.int64)
    else:
        entry_idx_arr = np.empty(0, dtype=np.int64)
        exit_idx_arr  = np.empty(0, dtype=np.int64)

    cursor  = 0
    balance = float(starting_balance)

    for i, snap in enumerate(trade_snapshots):
        e = int(entry_idx_arr[i])
        x = int(exit_idx_arr[i])

        if e > cursor:
            pos[cursor:e] = balance

        if x > e:
            pos[e:x] = float(snap["starting_balance"]) * (
                close_arr[e:x] / float(snap["entry_price"])
            )

        balance = float(snap["ending_balance"])
        cursor  = x

    if cursor < n_candles:
        pos[cursor:] = balance

    portfolio    = pd.Series(pos, index=df.index, dtype=float)
    daily_values = portfolio.resample("D").last().ffill()
    daily_values = (
        daily_values
        .reindex(full_days, method="ffill")
        .fillna(float(starting_balance))
    )
    return daily_values.astype(float)


# ── Drawdown analysis ─────────────────────────────────────────────────────────

def _drawdown_stats(portfolio_values: pd.Series) -> dict[str, Any]:
    """
    Always returns a dict with all drawdown fields.
    Finds the worst peak-to-trough drawdown, its dates, duration, and recovery.
    """
    empty: dict[str, Any] = {
        "max_drawdown":            0.0,
        "max_drawdown_duration":   0,
        "worst_drawdown_start_date": None,
        "worst_drawdown_end_date":   None,
        "drawdown_duration_days":  0,
        "recovery_date":           None,
        "recovery_time_days":      0,
    }

    if portfolio_values is None or portfolio_values.empty:
        return empty

    running_peak = portfolio_values.cummax()
    drawdowns    = ((portfolio_values / running_peak) - 1.0) * 100.0
    max_drawdown = abs(float(drawdowns.min())) if not drawdowns.empty else 0.0

    if max_drawdown <= 0.0:
        return empty

    # Index of worst trough
    trough_idx = drawdowns.idxmin()
    # Start of THIS drawdown episode: the most recent equity high (drawdown == 0)
    # at or before the trough — i.e. the peak the curve actually declined from.
    # Using idxmax() over the prefix returns the EARLIEST occurrence of the peak
    # value, which massively overstates the drawdown duration when the curve
    # revisits the same high several times before its worst drop (e.g. a flat
    # equity curve that recovers to break-even between drawdowns). The first bar
    # always has drawdown 0 (value == running peak), so this slice is never empty.
    dd_to_trough = drawdowns.loc[:trough_idx]
    peak_idx   = dd_to_trough[dd_to_trough >= 0.0].index[-1]
    peak_value = float(portfolio_values.loc[peak_idx])

    # First date after trough where portfolio recovers to peak value
    after_trough     = portfolio_values.loc[trough_idx:]
    recovery_series  = after_trough[after_trough >= peak_value]
    recovery_idx     = recovery_series.index[0] if not recovery_series.empty else None

    # Worst drawdown duration: calendar days from peak to trough
    try:
        dd_duration_days = int((trough_idx - peak_idx).days)
    except Exception:
        dd_duration_days = 0

    # Recovery time: calendar days from trough back to the prior peak. None means
    # the curve never climbed back to its pre-drawdown peak within the backtest
    # window — that is NOT an instant/zero recovery, so downstream risk
    # classification must treat it as worst-case rather than best-case.
    try:
        recovery_time = int((recovery_idx - trough_idx).days) if recovery_idx is not None else None
    except Exception:
        recovery_time = None

    # Max consecutive days spent underwater (below any prior peak)
    underwater        = drawdowns < 0
    max_underwater    = 0
    current_streak    = 0
    for is_under in underwater:
        if is_under:
            current_streak += 1
            max_underwater  = max(max_underwater, current_streak)
        else:
            current_streak  = 0

    return {
        "max_drawdown":            max_drawdown,
        "max_drawdown_duration":   max_underwater,
        "worst_drawdown_start_date": str(peak_idx.date())     if peak_idx is not None else None,
        "worst_drawdown_end_date":   str(trough_idx.date())   if trough_idx is not None else None,
        "drawdown_duration_days":  dd_duration_days,
        "recovery_date":           str(recovery_idx.date())   if recovery_idx is not None else None,
        "recovery_time_days":      recovery_time,
    }


# ── Statistical helpers ────────────────────────────────────────────────────────

def _annualized_sharpe(daily_returns: pd.Series) -> float:
    """Annualized Sharpe ratio (risk-free rate = 0). daily_returns in decimal form."""
    std_dev = float(daily_returns.std(ddof=1)) if len(daily_returns) > 1 else 0.0
    if std_dev <= 0:
        return 0.0
    return float((daily_returns.mean() / std_dev) * (TRADING_DAYS_PER_YEAR ** 0.5))


def _annualized_sortino(daily_returns: pd.Series) -> float:
    """Annualized Sortino ratio. daily_returns in decimal form."""
    downside     = daily_returns[daily_returns < 0]
    downside_std = float(downside.std(ddof=1)) if len(downside) > 1 else 0.0
    if downside_std <= 0:
        return 0.0
    return float((daily_returns.mean() / downside_std) * (TRADING_DAYS_PER_YEAR ** 0.5))


def _annualized_volatility(daily_returns_pct: pd.Series) -> float:
    """Annualized standard deviation of daily returns (in %)."""
    if len(daily_returns_pct) < 2:
        return 0.0
    return float(daily_returns_pct.std(ddof=1)) * (TRADING_DAYS_PER_YEAR ** 0.5)


def _annualized_downside_deviation(daily_returns_pct: pd.Series) -> float:
    """Annualized std dev of only the negative daily returns (in %)."""
    downside = daily_returns_pct[daily_returns_pct < 0]
    if len(downside) < 2:
        return 0.0
    return float(downside.std(ddof=1)) * (TRADING_DAYS_PER_YEAR ** 0.5)


def _historical_var_and_expected_shortfall(
    daily_returns_pct: pd.Series,
) -> tuple[float, float]:
    """
    Historical VaR at VAR_CONFIDENCE_LEVEL and Expected Shortfall (CVaR).
    Both returned as negative numbers indicating potential loss (in %).
    """
    if daily_returns_pct.empty:
        return 0.0, 0.0
    sorted_returns = daily_returns_pct.sort_values()
    cutoff_idx     = max(1, int(len(sorted_returns) * VAR_CONFIDENCE_LEVEL))
    var_95         = float(sorted_returns.iloc[cutoff_idx - 1])
    tail           = sorted_returns.iloc[:cutoff_idx]
    es_95          = float(tail.mean()) if not tail.empty else 0.0
    return _round(var_95), _round(es_95)


def _avg_trade_duration_days(
    entry_ts_sorted: pd.DatetimeIndex,
    exit_ts_sorted: pd.DatetimeIndex,
) -> float:
    """Mean calendar days between entry and exit across all trades.

    Vectorized. Caller passes the already-parsed timestamp arrays so we don't
    re-parse 2 × len(trades) strings.
    """
    n = len(entry_ts_sorted)
    if n == 0:
        return 0.0
    secs = (exit_ts_sorted.asi8 - entry_ts_sorted.asi8).astype(np.float64) / 1e9
    days = np.clip(secs / 86_400.0, 0.0, None)
    return float(days.mean())


def _trades_per_month(total_trades: int, num_days: int) -> float:
    """Average number of trades per calendar month."""
    if num_days <= 0:
        return 0.0
    return total_trades / (num_days / CALENDAR_DAYS_PER_MONTH)


def _longest_losing_streak(trades_sorted: list[Trade]) -> int:
    """Longest consecutive sequence of losing trades (pnl_pct ≤ 0).

    Caller passes trades already sorted by entry_ts so we skip the per-trade
    pd.to_datetime sort key that dominated this function before.
    """
    if not trades_sorted:
        return 0
    max_streak     = 0
    current_streak = 0
    for trade in trades_sorted:
        if float(trade.pnl_pct) <= 0:
            current_streak += 1
            max_streak      = max(max_streak, current_streak)
        else:
            current_streak  = 0
    return max_streak


# ── Diagnostic helpers ────────────────────────────────────────────────────────

# Every entry-gate diagnostic field, paired with a human-readable cause. Order
# matters only for tie-breaking when reporting the dominant blocker.
_ENTRY_BLOCK_REASONS: tuple[tuple[str, str], ...] = (
    ("entry_blocked_session_last",
     "the strategy's objective is intraday but its timeframe spans a full "
     "session (e.g. a 1d timeframe), so every entry would have to be squared "
     "off on the same bar it opened — set the objective to 'positional' for "
     "daily/swing strategies"),
    ("entry_blocked_daily_cap",        "the daily loss cap halted new entries"),
    ("entry_blocked_max_trades",       "the max-trades-per-day limit was reached"),
    ("entry_blocked_htf",              "a higher-timeframe trend gate was not satisfied"),
    ("entry_blocked_time_exit",        "the signals fired past the intraday time-exit cutoff"),
    ("entry_blocked_entry_window",     "the signals fired outside the allowed entry window"),
    ("entry_blocked_consecutive_losses","the consecutive-loss circuit breaker was active"),
    ("entry_blocked_cooldown",         "a post-trade cooldown was active"),
    ("entry_blocked_spread",           "the estimated spread exceeded the max-spread gate"),
    ("entry_blocked_gap",              "the gap filter rejected the session"),
    ("entry_blocked_confirmation",     "the signal never held for the required confirmation bars"),
    ("entry_blocked_rsi_band",         "the RSI entry-band gate rejected the bars"),
    ("entry_blocked_volume_ratio",     "the volume-ratio gate rejected the bars"),
    ("entry_blocked_volatility",       "the volatility-band gate rejected the bars"),
    ("entry_blocked_regime",           "the market regime was not in the allow-list"),
    ("entry_blocked_relative_strength","the relative-strength gate rejected the bars"),
    ("entry_blocked_event",            "the entries fell on configured blackout/event dates"),
    ("entry_blocked_lunch_lull",       "the entries fell inside the midday lull window"),
)


def _build_no_trade_hints(diagnostics: list[dict], df: pd.DataFrame) -> str:
    if not diagnostics:
        return ""

    total           = len(diagnostics)
    entry_evaluated = sum(1 for d in diagnostics if d.get("entry_evaluated"))
    entry_signals   = sum(1 for d in diagnostics if d.get("entry_signal"))

    if entry_evaluated == 0:
        return (
            f"All {total} candles were consumed by indicator warm-up. "
            "Fetch more historical data so indicators are ready before the evaluation window."
        )
    if entry_signals == 0:
        return (
            f"Entry conditions were evaluated on {entry_evaluated} of {total} candles "
            "but never returned True. Check that your entry condition logic is correct "
            "and that the indicators are generating valid values."
        )

    # Entries fired but produced no trades — report the dominant ACTUAL blocker
    # rather than a hardcoded guess. Each diagnostic counts the bars where that
    # gate was the reason the entry didn't fill.
    block_counts = [
        (reason, sum(1 for d in diagnostics if d.get(field)))
        for field, reason in _ENTRY_BLOCK_REASONS
    ]
    block_counts = [(r, c) for r, c in block_counts if c > 0]

    base = (
        f"Entry conditions fired {entry_signals} time(s) across {entry_evaluated} "
        "eligible candles but no trade filled"
    )
    if not block_counts:
        return base + " (no entry gate recorded a block — review entry/exit configuration)."

    block_counts.sort(key=lambda rc: rc[1], reverse=True)
    dominant_reason, dominant_count = block_counts[0]
    return f"{base}: most often ({dominant_count}×) because {dominant_reason}."


def _build_diagnostic_summary(diagnostics: list[dict]) -> dict:
    if not diagnostics:
        return {}
    summary = {
        "total_candles":     len(diagnostics),
        "entry_evaluated":   sum(1 for d in diagnostics if d.get("entry_evaluated")),
        "entry_signals":     sum(1 for d in diagnostics if d.get("entry_signal")),
        "exit_signals":      sum(1 for d in diagnostics if d.get("exit_signal")),
        "stop_hits":         sum(1 for d in diagnostics if d.get("stop_hit")),
        "tp_hits":           sum(1 for d in diagnostics if d.get("tp_hit")),
    }
    # Per-gate block counts (0 omitted) so callers see exactly what rejected entries.
    for field, _reason in _ENTRY_BLOCK_REASONS:
        count = sum(1 for d in diagnostics if d.get(field))
        if count:
            summary[f"{field}_count"] = count
    # Preserve the two legacy keys other code/tests may read.
    summary["daily_cap_blocks"]  = sum(1 for d in diagnostics if d.get("entry_blocked_daily_cap"))
    summary["max_trades_blocks"] = sum(1 for d in diagnostics if d.get("entry_blocked_max_trades"))
    return summary
